// Generates prompts/what-claude-sees.md and prompts/what-codex-sees.md at the repo
// root from the live server and the real renderers, so the published text is
// always what c2c actually sends. `test/prompt-docs.test.ts` fails on drift.
//
//   bun run gen:prompt-docs

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import {
  PROTOCOL_INSTRUCTIONS,
  renderDeltaContract,
  renderGoalContract,
  renderObjectiveDetails,
  type DeltaContract,
  type GoalContract,
} from "../src/contracts.ts";

const mcpDir = join(dirname(fileURLToPath(import.meta.url)), "..");
export const CLAUDE_DOC = join(mcpDir, "..", "prompts", "what-claude-sees.md");
export const CODEX_DOC = join(mcpDir, "..", "prompts", "what-codex-sees.md");
const GENERATED = "<!-- Generated by `bun run gen:prompt-docs` in mcp/. Do not edit by hand. -->";

/** Fences verbatim text with a fence longer than any backtick run inside it. */
function fence(text: string, lang = "") {
  const longest = Math.max(2, ...(text.match(/`+/g) ?? []).map((run) => run.length));
  const f = "`".repeat(longest + 1);
  return `${f}${lang}\n${text}\n${f}`;
}

export async function renderClaudeDoc(): Promise<string> {
  const env: Record<string, string> = { ...(process.env as Record<string, string>), C2C_LOG_LEVEL: "silent" };
  delete env.GOAL_OBJECTIVE_MAX; // document the default budget
  const transport = new StdioClientTransport({
    command: "bun",
    args: [join(mcpDir, "src", "server.ts")],
    cwd: mcpDir,
    env,
  });
  const client = new Client({ name: "gen-prompt-docs", version: "1" });
  await client.connect(transport);
  try {
    const instructions = client.getInstructions() ?? "";
    const prompt: any = await client.getPrompt({ name: "c2c-workflow" });
    const workflow = String(prompt.messages[0].content.text).trim();
    const { tools } = await client.listTools();

    const toolSections = tools.map((tool) => {
      const props = Object.entries<any>((tool.inputSchema as any).properties ?? {});
      const required = new Set<string>((tool.inputSchema as any).required ?? []);
      const params = props.map(([name, schema]) =>
        `- \`${name}\`${required.has(name) ? "" : " (optional)"}${schema.description ? ` — ${schema.description}` : ""}`);
      return [`### \`${tool.name}\``, "", tool.description ?? "", ...(params.length ? ["", ...params] : [])].join("\n");
    });

    return [
      GENERATED,
      "",
      "# What Claude Sees",
      "",
      "Everything the c2c MCP server puts in front of Claude Code, verbatim. Read this before writing a project's `CLAUDE.md`: anything below is already delivered, so `CLAUDE.md` only needs what is specific to your project (session startup, extra review rules, project constraints).",
      "",
      "| Layer | When Claude sees it | Size |",
      "|---|---|---|",
      `| [Server instructions](#1-server-instructions) | Automatically, injected into the system prompt on connect | ${instructions.length} chars |`,
      `| [\`c2c-workflow\` Prompt](#2-the-c2c-workflow-prompt) | Only when the user runs \`/mcp__<server>__c2c-workflow\` | ${workflow.length} chars |`,
      `| [Tool descriptions](#3-tool-descriptions) | Automatically, as tool definitions | ${tools.length} tools |`,
      "",
      "## 1. Server instructions",
      "",
      "Always in context, so kept short. They activate only when the user asks to delegate to Codex; ordinary requests are handled as usual.",
      "",
      fence(instructions, "text"),
      "",
      "## 2. The `c2c-workflow` Prompt",
      "",
      "The full rules: role, workflow, Goal/Delta Contract formats, review protocol. MCP Prompts are user-invoked; in Claude Code type `/mcp__codex__c2c-workflow` (the middle segment is whatever you named the server).",
      "",
      fence(workflow, "markdown"),
      "",
      "## 3. Tool descriptions",
      "",
      "Shipped with every install and read whenever Claude calls a tool, so hard limits (objective budget, context-file existence) are stated here rather than only in the Prompt.",
      "",
      toolSections.join("\n\n"),
      "",
    ].join("\n");
  } finally {
    await client.close();
  }
}

const EXAMPLE_GOAL: GoalContract = {
  goal: "`topWords(text, n)` in src/wordfreq.js returns the n most frequent words as [word, count] pairs, case-insensitive, punctuation ignored, ties broken alphabetically.",
  constraints: ["Only modify files needed for this task."],
  success_conditions: [
    "`npm test` exits 0; test/wordfreq.test.js covers case folding, punctuation, ties, and n <= 0.",
    "Deleting the alphabetical tie-break makes `npm test` fail.",
  ],
};

const EXAMPLE_DELTA: DeltaContract = {
  findings: ["src/wordfreq.js:12 — `topWords(text, 0)` returns one word; it must return []."],
  failed_conditions: ["`npm test` exits 0; test/wordfreq.test.js covers case folding, punctuation, ties, and n <= 0."],
};

/** Strips the shared protocol prefix, asserting the rendered prompt really starts with it. */
function contractPart(prompt: string): string {
  if (!prompt.startsWith(PROTOCOL_INSTRUCTIONS)) throw new Error("rendered prompt does not start with PROTOCOL_INSTRUCTIONS");
  return prompt.slice(PROTOCOL_INSTRUCTIONS.length).trimStart();
}

export function renderCodexDoc(): string {
  const { objective } = renderObjectiveDetails(EXAMPLE_GOAL, 2000);
  return [
    GENERATED,
    "",
    "# What Codex Sees",
    "",
    "What Codex receives for each job. Read this before writing a project's `AGENTS.md`: the protocol below (execution rules, self-verification, handoff format, rework rules) is sent with every contract, so `AGENTS.md` only needs what is specific to your project (toolchain and commands, file/dependency boundaries).",
    "",
    "| Layer | Source |",
    "|---|---|",
    "| Codex's own system instructions | Codex itself |",
    "| `AGENTS.md` | Loaded by Codex from the job's repository tree (c2c does not inject it) |",
    "| Turn prompt | c2c: the [protocol](#1-protocol-every-job) followed by a [Goal](#2-goal-contract-codex_implement) or [Delta](#4-delta-contract-codex_rework) Contract |",
    "| [Thread-goal objective](#3-thread-goal-objective) | c2c: a compact restatement the `/goal` loop audits before declaring completion (max 2000 chars by default) |",
    "",
    "## 1. Protocol (every job)",
    "",
    "The fixed first part of every turn prompt, identical for Goal and Delta Contracts.",
    "",
    fence(PROTOCOL_INSTRUCTIONS, "markdown"),
    "",
    "## 2. Goal Contract (`codex_implement`)",
    "",
    "Appended after the protocol for a new job. Example contract:",
    "",
    fence(contractPart(renderGoalContract(EXAMPLE_GOAL)), "markdown"),
    "",
    "## 3. Thread-goal objective",
    "",
    "Set via `thread/goal/set` for the same job. It is built from `goal` and every `success_condition`; the handoff requirement is appended automatically, so contracts should not list it.",
    "",
    fence(objective, "text"),
    "",
    "## 4. Delta Contract (`codex_rework`)",
    "",
    "Appended after the protocol when review fails; sent into the same thread, where the original goal and objective re-engage. Example:",
    "",
    fence(contractPart(renderDeltaContract(EXAMPLE_DELTA)), "markdown"),
    "",
  ].join("\n");
}

if (import.meta.main) {
  writeFileSync(CLAUDE_DOC, await renderClaudeDoc());
  writeFileSync(CODEX_DOC, renderCodexDoc());
  console.log(`wrote ${CLAUDE_DOC}\nwrote ${CODEX_DOC}`);
}
